In [1]:
import numpy as np

In [3]:
arr1 = np.arange(3)
arr2 = np.arange(4,7)
print(arr1)
print(arr2)

[0 1 2]
[4 5 6]


In [4]:
mat1 = np.arange(9).reshape(3,3)
mat2 = np.arange(9,18).reshape(3,3)
print(mat1)
print(mat2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
matHstack = np.hstack([mat1,mat2])
print(matHstack)

[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


In [9]:
matVertStack = np.vstack([mat1,mat2])
print(matVertStack)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [ ]:
arr1 = np.array([1.002,2.3,9.872])
print(round(arr1[-1]))

10


In [ ]:
# view vs copy
org = np.array([1,2,3,4])
tmp = org # given by the reference
hlp = org.copy() # now only copy on changing the hlp do not chnage the org
x = org.view() # copied by the reference
tmp[0]=-1
hlp[0]=10
x[2]=88
print(org)

[-1  2 88  4]


In [23]:
#unique values and the frequency
arr = np.array([1,2,3,4,5,1,1,2,3,3,5,2,2,2,23,4])
unique = np.unique(arr)
print(unique)
unique , cnt = np.unique(arr , return_counts=True)
x  = dict(zip(unique,cnt))
print(x)

[ 1  2  3  4  5 23]
{np.int64(1): np.int64(3), np.int64(2): np.int64(5), np.int64(3): np.int64(3), np.int64(4): np.int64(2), np.int64(5): np.int64(2), np.int64(23): np.int64(1)}


In [25]:
tmp = np.where(arr>4,-1,arr)
print(tmp)

[ 1  2  3  4 -1  1  1  2  3  3 -1  2  2  2 -1  4]


In [33]:
rng = np.random.default_rng()

print(rng.random(5))

[0.86099969 0.46268472 0.47598968 0.17981568 0.51496578]


In [36]:
print(np.random.randint(1,10,5))
print(10*np.random.random(10))

[7 8 4 8 7]
[3.37241437e+00 6.79614811e+00 7.60958900e+00 1.72947826e-03
 6.62452103e+00 9.21656650e+00 3.52679929e+00 8.08756353e+00
 8.80262072e+00 3.34248822e+00]


In [37]:
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
mat2
mat2[0,2]=7
mat2[1,2]=8

In [42]:
print(np.linalg.inv(mat2))

[[-3.875       2.41666667  0.45833333]
 [ 3.5        -2.         -0.5       ]
 [ 0.125      -0.25        0.125     ]]


In [45]:
print(round(np.linalg.det(mat2)))

-24


In [ ]:
print(np.clip(mat1,2,6)) # basically outliers ko boundary me convert krta h 

[[2 2 2]
 [3 4 5]
 [6 6 6]]


In [47]:
print(np.diff(mat1))

[[1 1]
 [1 1]
 [1 1]]


In [48]:
arr

array([ 1,  2,  3,  4,  5,  1,  1,  2,  3,  3,  5,  2,  2,  2, 23,  4])

In [50]:
print(arr[arr>10])

[23]


In [ ]:
print(np.where(arr>10 and arr<20),0,arr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()