# NumPy Comprehensive Demo for B.Tech Students

This notebook is a **hands-on, classroom-ready guide to NumPy**.

### Learning outcomes
By the end of this notebook, students should be able to:

- Explain why NumPy is used instead of ordinary Python lists for numerical computing.
- Create and inspect NumPy arrays.
- Understand dimensions, shape, size, axes, dtype, indexing and slicing.
- Perform vectorized arithmetic and comparisons.
- Use broadcasting correctly.
- Reshape, flatten, transpose, concatenate and split arrays.
- Perform aggregation and statistical operations along axes.
- Work with Boolean masks and conditional selection.
- Sort, search and find unique values.
- Understand views vs copies.
- Use random number generation safely with modern NumPy.
- Perform linear algebra operations.
- Handle missing values and NaNs.
- Apply common operations to real ML-style datasets.
- Write efficient NumPy code using vectorization instead of unnecessary Python loops.

> **Suggested teaching style:** Run the notebook cell by cell and ask students to predict the output before executing each important example.

## 1. Import NumPy and check the version

In [2]:
# NumPy is normally imported with the alias np.
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.2


## 2. Why NumPy?

A Python list can store numbers, but NumPy arrays are designed specifically for numerical computation.

### Python list
- General-purpose container
- Can contain mixed data types
- Arithmetic usually requires explicit loops

### NumPy ndarray
- Homogeneous numerical data is stored efficiently
- Supports vectorized operations
- Supports multidimensional arrays
- Provides fast mathematical, statistical and linear-algebra operations

The central object in NumPy is the **ndarray** (N-dimensional array).

In [3]:
# Python list
marks = [70, 80, 90, 60]

# NumPy array
marks_np = np.array(marks)

print("Python list :", marks)
print("NumPy array :", marks_np)

# Vectorized operation: add 5 marks to every student
print("Updated marks:", marks_np + 5)

Python list : [70, 80, 90, 60]
NumPy array : [70 80 90 60]
Updated marks: [75 85 95 65]


## 3. Creating NumPy arrays

In [4]:
# 1-D array
a = np.array([10, 20, 30, 40, 50])
print("1-D:", a)

# 2-D array
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("\n2-D:\n", b)

# 3-D array
c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3-D:\n", c)

1-D: [10 20 30 40 50]

2-D:
 [[1 2 3]
 [4 5 6]]

3-D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Important array terminology

For an array:

- `ndim` → number of dimensions
- `shape` → size along each dimension
- `size` → total number of elements
- `dtype` → data type of elements
- `itemsize` → bytes used by one element

In [4]:
print("a =", a)
print("ndim   :", a.ndim)
print("shape  :", a.shape)
print("size   :", a.size)
print("dtype  :", a.dtype)
print("itemsize:", a.itemsize)

print("\nFor b:")
print("ndim   :", b.ndim)
print("shape  :", b.shape)
print("size   :", b.size)
print("dtype  :", b.dtype)

a = [10 20 30 40 50]
ndim   : 1
shape  : (5,)
size   : 5
dtype  : int64
itemsize: 8

For b:
ndim   : 2
shape  : (2, 3)
size   : 6
dtype  : int64


## 4. Common array creation functions

In [6]:
# np.zeros
zeros = np.zeros((3, 4))
print("zeros:\n", zeros)

# np.ones
ones = np.ones((2, 3))
print("\nones:\n", ones)

# np.full
full = np.full((2, 4), 7)
print("\nfull:\n", full)

# np.empty creates an array without initializing values.
# Do NOT assume it contains zeros.
empty = np.empty((2, 3))
print("\nempty:\n", empty)

# Identity matrix
identity = np.eye(4)
print("\nidentity:\n", identity)

zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

full:
 [[7 7 7 7]
 [7 7 7 7]]

empty:
 [[1. 1. 1.]
 [1. 1. 1.]]

identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 5. arange(), linspace() and logarithmic spacing

In [5]:
# arange(start, stop, step)
x = np.arange(0, 10, 2)
print("arange:", x)

# Stop value is normally excluded.
x2 = np.arange(1, 6)
print("arange(1, 6):", x2)

# linspace(start, stop, number_of_values)
y = np.linspace(0, 1, 6)
print("linspace:", y)

# Useful for plotting/math problems
angles = np.linspace(0, 2*np.pi, 9)
print("Angles:", angles)

# Logarithmically spaced values
log_values = np.logspace(0, 3, 5)
print("logspace:", log_values)

arange: [0 2 4 6 8]
arange(1, 6): [1 2 3 4 5]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]
Angles: [0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
logspace: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


## 6. Data types (dtype)

In [8]:
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1, 2, 3], dtype=np.float64)
bool_array = np.array([True, False, True])

print(int_array, int_array.dtype)
print(float_array, float_array.dtype)
print(bool_array, bool_array.dtype)

# Explicit conversion
x = np.array([1.2, 2.8, 3.9])
print("Original:", x)
print("As integer:", x.astype(int))

[1 2 3] int32
[1. 2. 3.] float64
[ True False  True] bool
Original: [1.2 2.8 3.9]
As integer: [1 2 3]


### Common dtypes

- `np.int32`, `np.int64`
- `np.float32`, `np.float64`
- `np.bool_`
- `np.complex64`, `np.complex128`
- Strings/object types also exist, but numerical arrays are the most common in ML.

**Important:** converting floating-point values to integers truncates the fractional part; it does not round.

## 7. Indexing in 1-D arrays

In [9]:
x = np.array([10, 20, 30, 40, 50])

print("First element :", x[0])
print("Second element:", x[1])
print("Last element  :", x[-1])
print("Second last   :", x[-2])

# Change an element
x[2] = 999
print("After modification:", x)

First element : 10
Second element: 20
Last element  : 50
Second last   : 40
After modification: [ 10  20 999  40  50]


## 8. Indexing in 2-D arrays

In [10]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("A:\n", A)

# A[row, column]
print("A[0, 0] =", A[0, 0])
print("A[1, 2] =", A[1, 2])
print("Last element =", A[-1, -1])

# Complete first row
print("First row:", A[0])

# Complete second column
print("Second column:", A[:, 1])

A:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
A[0, 0] = 10
A[1, 2] = 60
Last element = 90
First row: [10 20 30]
Second column: [20 50 80]


## 9. Slicing

General form:

`array[start:stop:step]`

For 2-D arrays:

`array[row_slice, column_slice]`

In [6]:
x = np.arange(1,10)
print("x:", x)

print("x[2:7] :", x[2:7])
print("x[:5]  :", x[:5])
print("x[5:]  :", x[5:])
print("x[::2] :", x[::2])
print("x[::-1]:", x[::-1])

A = np.arange(1, 17).reshape(4, 4)
print("\nA:\n", A)

print("\nTop-left 2x2:\n", A[:2, :2])
print("\nFirst two rows:\n", A[:2, :])
print("\nLast two columns:\n", A[:, -2:])
print("\nEvery alternate row:\n", A[::2, :])

x: [1 2 3 4 5 6 7 8 9]
x[2:7] : [3 4 5 6 7]
x[:5]  : [1 2 3 4 5]
x[5:]  : [6 7 8 9]
x[::2] : [1 3 5 7 9]
x[::-1]: [9 8 7 6 5 4 3 2 1]

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Top-left 2x2:
 [[1 2]
 [5 6]]

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]

Last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

Every alternate row:
 [[ 1  2  3  4]
 [ 9 10 11 12]]


## 10. Vectorized arithmetic

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)

# Scalar broadcasting
print("a + 100 =", a + 100)
print("a * 10  =", a * 10)

a + b = [11 22 33 44]
a - b = [ -9 -18 -27 -36]
a * b = [ 10  40  90 160]
a / b = [0.1 0.1 0.1 0.1]
a ** 2 = [ 1  4  9 16]
a + 100 = [101 102 103 104]
a * 10  = [10 20 30 40]


### Element-wise operations vs matrix operations

This distinction is extremely important.

- `A * B` → element-wise multiplication
- `A @ B` → matrix multiplication
- `np.matmul(A, B)` → matrix multiplication
- `np.dot(A, B)` → dot product / matrix multiplication depending on dimensions

Do not confuse `*` with matrix multiplication.

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A * B (element-wise):\n", A * B)
print("\nA @ B (matrix multiplication):\n", A @ B)

A * B (element-wise):
 [[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
 [[19 22]
 [43 50]]


## 11. Comparison operators and Boolean arrays

In [14]:
x = np.array([10, 20, 30, 40, 50])

print(x > 25)
print(x == 30)
print(x != 30)
print(x <= 30)

# Combine conditions with &, | and ~
print("\nBetween 20 and 40:")
print((x >= 20) & (x <= 40))

print("\nLess than 20 OR greater than 40:")
print((x < 20) | (x > 40))

[False False  True  True  True]
[False False  True False False]
[ True  True False  True  True]
[ True  True  True False False]

Between 20 and 40:
[False  True  True  True False]

Less than 20 OR greater than 40:
[ True False False False  True]


**Important:** With NumPy arrays, use `&`, `|`, and `~` for element-wise logical operations.

Use parentheses around each condition:

`(x > 10) & (x < 50)`

Do not write:

`x > 10 and x < 50`

## 12. Boolean masking / filtering

In [15]:
marks = np.array([35, 78, 92, 41, 66, 29, 88])

passed = marks >= 40

print("Marks :", marks)
print("Mask  :", passed)
print("Passed:", marks[passed])

# Directly use the condition
print("Marks >= 70:", marks[marks >= 70])

# Multiple conditions
print("40 <= marks < 80:", marks[(marks >= 40) & (marks < 80)])

Marks : [35 78 92 41 66 29 88]
Mask  : [False  True  True  True  True False  True]
Passed: [78 92 41 66 88]
Marks >= 70: [78 92 88]
40 <= marks < 80: [78 41 66]


## 13. np.where()

In [16]:
marks = np.array([35, 78, 92, 41, 66, 29, 88])

# np.where(condition, value_if_true, value_if_false)
result = np.where(marks >= 40, "Pass", "Fail")
print(result)

# Add grace marks to students below 40
adjusted = np.where(marks < 40, marks + 5, marks)
print("Adjusted marks:", adjusted)

['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']
Adjusted marks: [40 78 92 41 66 34 88]


## 14. Mathematical functions

In [17]:
x = np.array([0, np.pi/2, np.pi])

print("sin:", np.sin(x))
print("cos:", np.cos(x))
print("sqrt:", np.sqrt(np.array([1, 4, 9, 16])))
print("exp:", np.exp(np.array([0, 1, 2])))
print("log:", np.log(np.array([1, np.e, np.e**2])))

# Element-wise absolute value
y = np.array([-10, -3, 0, 5, 12])
print("abs:", np.abs(y))

sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sqrt: [1. 2. 3. 4.]
exp: [1.         2.71828183 7.3890561 ]
log: [0. 1. 2.]
abs: [10  3  0  5 12]


## 15. Aggregation functions

In [18]:
marks = np.array([55, 72, 91, 68, 84, 73])

print("sum :", np.sum(marks))
print("mean:", np.mean(marks))
print("min :", np.min(marks))
print("max :", np.max(marks))
print("std :", np.std(marks))
print("var :", np.var(marks))
print("median:", np.median(marks))

sum : 443
mean: 73.83333333333333
min : 55
max : 91
std : 11.48066006619635
var : 131.80555555555557
median: 72.5


## 16. Axis: one of the most important concepts

For a 2-D array:

- `axis=0` → operate **down the rows**, producing one result per column
- `axis=1` → operate **across the columns**, producing one result per row

Think carefully about the dimension that is being **collapsed**.

In [19]:
marks = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [90, 95, 88]
])

print("Marks:\n", marks)

print("\nColumn-wise mean (axis=0):", np.mean(marks, axis=0))
print("Row-wise mean    (axis=1):", np.mean(marks, axis=1))

print("\nColumn-wise maximum:", np.max(marks, axis=0))
print("Row-wise maximum   :", np.max(marks, axis=1))

print("\nColumn-wise sum:", np.sum(marks, axis=0))
print("Row-wise sum   :", np.sum(marks, axis=1))

Marks:
 [[80 70 90]
 [60 75 85]
 [90 95 88]]

Column-wise mean (axis=0): [76.66666667 80.         87.66666667]
Row-wise mean    (axis=1): [80.         73.33333333 91.        ]

Column-wise maximum: [90 95 90]
Row-wise maximum   : [90 85 95]

Column-wise sum: [230 240 263]
Row-wise sum   : [240 220 273]


## 17. keepdims

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row_mean = np.mean(A, axis=1)
row_mean_keep = np.mean(A, axis=1, keepdims=True)

print("Normal result:")
print(row_mean)
print("Shape:", row_mean.shape)

print("\nWith keepdims=True:")
print(row_mean_keep)
print("Shape:", row_mean_keep.shape)

Normal result:
[2. 5.]
Shape: (2,)

With keepdims=True:
[[2.]
 [5.]]
Shape: (2, 1)


## 18. Reshaping arrays

In [21]:
x = np.arange(1, 13)
print("Original:", x)
print("Shape:", x.shape)

A = x.reshape(3, 4)
print("\n3 x 4:\n", A)

B = x.reshape(4, 3)
print("\n4 x 3:\n", B)

# One dimension can be inferred using -1
C = x.reshape(3, -1)
print("\n3 x inferred:\n", C)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

3 x 4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

4 x 3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

3 x inferred:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Reshape rule

The total number of elements must remain unchanged.

For example:

12 elements → valid shapes include `(3, 4)`, `(4, 3)`, `(2, 6)`, `(12,)`

But `(5, 3)` is invalid because it requires 15 elements.

In [34]:
try:
    x.reshape(5, 3)
except ValueError as e:
    print("Error:", e)

Error: cannot reshape array of size 3 into shape (5,3)


## 19. flatten(), ravel() and reshape(-1)

In [35]:
A = np.arange(1, 7).reshape(2, 3)

print("A:\n", A)

print("\nflatten:", A.flatten())
print("ravel  :", A.ravel())
print("reshape(-1):", A.reshape(-1))

A:
 [[1 2 3]
 [4 5 6]]

flatten: [1 2 3 4 5 6]
ravel  : [1 2 3 4 5 6]
reshape(-1): [1 2 3 4 5 6]


- `flatten()` returns a copy.
- `ravel()` generally returns a view when possible.
- `reshape(-1)` is commonly used to convert an array to one dimension.

The view/copy distinction matters when you modify the result.

## 20. Transpose

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("A:\n", A)
print("\nA.T:\n", A.T)
print("\nnp.transpose(A):\n", np.transpose(A))

A:
 [[1 2 3]
 [4 5 6]]

A.T:
 [[1 4]
 [2 5]
 [3 6]]

np.transpose(A):
 [[1 4]
 [2 5]
 [3 6]]


## 21. Adding/removing dimensions

In [37]:
x = np.array([10, 20, 30])

print("x shape:", x.shape)

row = x[np.newaxis, :]
column = x[:, np.newaxis]

print("\nRow shape:", row.shape)
print(row)

print("\nColumn shape:", column.shape)
print(column)

# squeeze removes dimensions of size 1
print("\nSqueezed row:", np.squeeze(row))

x shape: (3,)

Row shape: (1, 3)
[[10 20 30]]

Column shape: (3, 1)
[[10]
 [20]
 [30]]

Squeezed row: [10 20 30]


## 22. Concatenation, stacking and splitting

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate([a, b]))
print("hstack     :", np.hstack([a, b]))
print("vstack     :", np.vstack([a, b]))

# Stack creates a new axis
print("\nstack axis=0:")
print(np.stack([a, b], axis=0))

print("\nstack axis=1:")
print(np.stack([a, b], axis=1))

concatenate: [1 2 3 4 5 6]
hstack     : [1 2 3 4 5 6]
vstack     : [[1 2 3]
 [4 5 6]]

stack axis=0:
[[1 2 3]
 [4 5 6]]

stack axis=1:
[[1 4]
 [2 5]
 [3 6]]


In [39]:
A = np.arange(1, 13).reshape(3, 4)
print("A:\n", A)

print("\nHorizontal split:")
print(np.hsplit(A, 2))

print("\nVertical split:")
print(np.vsplit(A, 3))

A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Horizontal split:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]

Vertical split:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


## 23. Broadcasting — essential for ML

In [40]:
# A scalar broadcasts to every element
x = np.array([1, 2, 3])
print(x + 10)

# A row vector can be added to every row
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

bias = np.array([10, 20, 30])
print("\nA + bias:\n", A + bias)

[11 12 13]

A + bias:
 [[11 22 33]
 [14 25 36]]


### Broadcasting intuition

Suppose:

- `A.shape == (3, 4)`
- `b.shape == (4,)`

NumPy treats `b` as compatible with each row of `A`.

Another common example:

- `A.shape == (3, 1)`
- `b.shape == (1, 4)`

The result can have shape `(3, 4)`.

Broadcasting is heavily used in machine learning for normalization, biases, feature scaling and batch operations.

In [41]:
A = np.arange(1, 4).reshape(3, 1)
B = np.arange(10, 14).reshape(1, 4)

print("A shape:", A.shape)
print("B shape:", B.shape)

C = A + B
print("\nA + B:\n", C)
print("Result shape:", C.shape)

A shape: (3, 1)
B shape: (1, 4)

A + B:
 [[11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]]
Result shape: (3, 4)


## 24. Sorting and ordering

In [42]:
x = np.array([40, 10, 70, 20, 50])

print("Original:", x)
print("np.sort:", np.sort(x))

# argsort returns indices that would sort the array
indices = np.argsort(x)
print("argsort indices:", indices)
print("Sorted using indices:", x[indices])

Original: [40 10 70 20 50]
np.sort: [10 20 40 50 70]
argsort indices: [1 3 0 4 2]
Sorted using indices: [10 20 40 50 70]


## 25. Search functions: argmax, argmin, where

In [9]:
x = np.array([45, 82, 67, 91, 55])

print("Maximum value:", np.max(x))
print("Maximum index:", np.argmax(x))

print("Minimum value:", np.min(x))
print("Minimum index:", np.argmin(x))

print("Indices where x > 70:", np.where(x > 70)[0][0])

Maximum value: 91
Maximum index: 3
Minimum value: 45
Minimum index: 0
Indices where x > 70: 1


## 26. Unique values and frequencies

In [44]:
x = np.array([10, 20, 10, 30, 20, 10, 40, 30])

unique, counts = np.unique(x, return_counts=True)

print("Unique values:", unique)
print("Counts:", counts)

print("\nFrequency mapping:")
for value, count in zip(unique, counts):
    print(value, "->", count)

Unique values: [10 20 30 40]
Counts: [3 2 2 1]

Frequency mapping:
10 -> 3
20 -> 2
30 -> 2
40 -> 1


## 27. Set operations

In [45]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7])

print("Union       :", np.union1d(a, b))
print("Intersection:", np.intersect1d(a, b))
print("Difference a-b:", np.setdiff1d(a, b))
print("Difference b-a:", np.setdiff1d(b, a))

Union       : [1 2 3 4 5 6 7]
Intersection: [4 5]
Difference a-b: [1 2 3]
Difference b-a: [6 7]


## 28. Random numbers — modern NumPy approach

In [46]:
# Prefer the modern Generator API.
rng = np.random.default_rng(seed=42)

print("Random integers:")
print(rng.integers(1, 10, size=10))

print("\nUniform random numbers:")
print(rng.random(5))

print("\nNormal distribution:")
print(rng.normal(loc=0, scale=1, size=5))

Random integers:
[1 7 6 4 4 8 1 7 2 1]

Uniform random numbers:
[0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]

Normal distribution:
[0.87939797 0.77779194 0.0660307  1.12724121 0.46750934]


## 29. Random sampling

In [11]:
rng = np.random.default_rng(7)

students = np.array(["A", "B", "C", "D", "E", "F"])

# Randomly select 3 students without replacement
sample = rng.choice(students, size=3, replace=False)
print("Sample:", sample)

# With replacement
sample_with_replacement = rng.choice(students, size=8, replace=True)
print("With replacement:", sample_with_replacement)

Sample: ['D' 'E' 'F']
With replacement: ['E' 'F' 'B' 'A' 'B' 'B' 'F' 'F']


## 30. Reproducibility

In [48]:
# A fixed seed produces reproducible random sequences.
rng1 = np.random.default_rng(123)
rng2 = np.random.default_rng(123)

a = rng1.random(5)
b = rng2.random(5)

print("Sequence 1:", a)
print("Sequence 2:", b)
print("Same?", np.array_equal(a, b))

Sequence 1: [0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
Sequence 2: [0.68235186 0.05382102 0.22035987 0.18437181 0.1759059 ]
Same? True


## 31. Probability simulation: rolling a die

In [49]:
rng = np.random.default_rng(42)

# Simulate 10,000 die rolls
rolls = rng.integers(1, 7, size=10000)

for face in range(1, 7):
    frequency = np.sum(rolls == face)
    probability = frequency / len(rolls)
    print(f"Face {face}: frequency={frequency}, probability={probability:.4f}")

Face 1: frequency=1681, probability=0.1681
Face 2: frequency=1718, probability=0.1718
Face 3: frequency=1662, probability=0.1662
Face 4: frequency=1671, probability=0.1671
Face 5: frequency=1643, probability=0.1643
Face 6: frequency=1625, probability=0.1625


## 32. Linear algebra basics

In [50]:
A = np.array([
    [2, 1],
    [1, 3]
], dtype=float)

b = np.array([5, 7], dtype=float)

print("A:\n", A)
print("b:", b)

# Solve Ax = b
x = np.linalg.solve(A, b)

print("\nSolution x:", x)
print("Check A @ x:", A @ x)

A:
 [[2. 1.]
 [1. 3.]]
b: [5. 7.]

Solution x: [1.6 1.8]
Check A @ x: [5. 7.]


## 33. Matrix inverse, determinant and eigenvalues

In [51]:
A = np.array([
    [4, 2],
    [1, 3]
], dtype=float)

print("Determinant:", np.linalg.det(A))
print("\nInverse:\n", np.linalg.inv(A))

eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Determinant: 10.000000000000002

Inverse:
 [[ 0.3 -0.2]
 [-0.1  0.4]]

Eigenvalues: [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


### Practical advice

Although `np.linalg.inv(A)` is useful for learning, **do not normally compute an inverse just to solve `Ax=b`**.

Prefer:

`np.linalg.solve(A, b)`

It is generally more numerically appropriate and efficient.

## 34. Dot product, inner product and norms

In [52]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Dot product:", np.dot(x, y))
print("Inner product:", np.inner(x, y))

print("L2 norm of x:", np.linalg.norm(x))
print("L1 norm of x:", np.linalg.norm(x, ord=1))

Dot product: 32
Inner product: 32
L2 norm of x: 3.7416573867739413
L1 norm of x: 6.0


## 35. Handling NaN and missing values

In [53]:
x = np.array([10.0, 20.0, np.nan, 40.0, 50.0])

print("Array:", x)
print("Is NaN:", np.isnan(x))

print("Normal mean:", np.mean(x))
print("NaN-safe mean:", np.nanmean(x))
print("NaN-safe sum:", np.nansum(x))
print("NaN-safe minimum:", np.nanmin(x))

Array: [10. 20. nan 40. 50.]
Is NaN: [False False  True False False]
Normal mean: nan
NaN-safe mean: 30.0
NaN-safe sum: 120.0
NaN-safe minimum: 10.0


## 36. Infinity and finite values

In [54]:
x = np.array([1, np.inf, -np.inf, np.nan, 5])

print("isfinite:", np.isfinite(x))
print("isinf   :", np.isinf(x))
print("isnan   :", np.isnan(x))

isfinite: [ True False False False  True]
isinf   : [False  True  True False False]
isnan   : [False False False  True False]


## 37. Rounding and numerical precision

In [55]:
x = np.array([1.23456, 2.71828, 3.14159])

print("round:", np.round(x, 2))
print("floor:", np.floor(x))
print("ceil :", np.ceil(x))

# Floating-point arithmetic can have tiny precision differences.
print("\n0.1 + 0.2 =", 0.1 + 0.2)
print("Is exactly 0.3?", 0.1 + 0.2 == 0.3)
print("Use np.isclose:", np.isclose(0.1 + 0.2, 0.3))

round: [1.23 2.72 3.14]
floor: [1. 2. 3.]
ceil : [2. 3. 4.]

0.1 + 0.2 = 0.30000000000000004
Is exactly 0.3? False
Use np.isclose: True


## 38. Views vs copies — very important

In [ ]:
original = np.array([10, 20, 30, 40, 50])

# Slicing generally creates a view
view = original[1:4]
view[0] = 999

print("Original after modifying view:", original)

# Explicit copy
original2 = np.array([10, 20, 30, 40, 50])
copy = original2[1:4].copy()
copy[0] = 999

print("Original after modifying copy:", original2)
print("Copy:", copy)

Original after modifying view: [ 10 999  30  40  50]
Original after modifying copy: [10 20 30 40 50]
Copy: [999  30  40]


### Rule of thumb

If you need an independent array:

`new_array = old_array.copy()`

This avoids accidental modification of the original data.

## 39. Copying an array vs assigning a variable

In [57]:
a = np.array([1, 2, 3])

# Assignment creates another reference to the same array
b = a
b[0] = 100

print("a after b[0] change:", a)

# copy() creates independent data
c = np.array([1, 2, 3])
d = c.copy()
d[0] = 100

print("c after d[0] change:", c)
print("d:", d)

a after b[0] change: [100   2   3]
c after d[0] change: [1 2 3]
d: [100   2   3]


## 40. Memory and array properties

In [58]:
A = np.zeros((100, 100), dtype=np.float64)

print("Shape:", A.shape)
print("Number of elements:", A.size)
print("Bytes per element:", A.itemsize)
print("Total bytes:", A.nbytes)
print("Approx MB:", A.nbytes / (1024**2))

Shape: (100, 100)
Number of elements: 10000
Bytes per element: 8
Total bytes: 80000
Approx MB: 0.0762939453125


## 41. Structured arrays — brief introduction

In [59]:
# Structured arrays allow fields with different data types.
students = np.array([
    (101, "Alice", 8.7),
    (102, "Bob", 7.9),
    (103, "Carol", 9.1)
], dtype=[
    ("id", "i4"),
    ("name", "U10"),
    ("cgpa", "f4")
])

print(students)
print("\nIDs:", students["id"])
print("Names:", students["name"])
print("CGPA:", students["cgpa"])

[(101, 'Alice', 8.7) (102, 'Bob', 7.9) (103, 'Carol', 9.1)]

IDs: [101 102 103]
Names: ['Alice' 'Bob' 'Carol']
CGPA: [8.7 7.9 9.1]


## 42. File I/O with NumPy

In [60]:
# Save and load binary NumPy arrays.
data = np.arange(12).reshape(3, 4)

np.save("demo_array.npy", data)
loaded = np.load("demo_array.npy")

print("Original:\n", data)
print("\nLoaded:\n", loaded)
print("Same data?", np.array_equal(data, loaded))

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Loaded:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Same data? True


## 43. Text/CSV-style data with NumPy

In [61]:
# A small demonstration of saving/loading numeric CSV data.
data = np.array([
    [101, 8.5, 72],
    [102, 7.9, 81],
    [103, 9.1, 91]
])

np.savetxt("students.csv", data, delimiter=",", fmt="%.2f")
loaded_csv = np.loadtxt("students.csv", delimiter=",")

print(loaded_csv)

[[101.    8.5  72. ]
 [102.    7.9  81. ]
 [103.    9.1  91. ]]


For serious CSV/tabular-data processing, students should also learn **Pandas**.

NumPy is the foundation for numerical arrays; Pandas adds labeled rows/columns and richer table operations.

## 44. Performance: Python loop vs vectorization

In [62]:
import time

n = 1_000_000
x = np.arange(n, dtype=np.float64)

# Python list computation
python_list = list(range(n))

start = time.perf_counter()
result_list = [v * 2 + 1 for v in python_list]
list_time = time.perf_counter() - start

# NumPy vectorized computation
start = time.perf_counter()
result_numpy = x * 2 + 1
numpy_time = time.perf_counter() - start

print(f"Python list comprehension: {list_time:.6f} seconds")
print(f"NumPy vectorization     : {numpy_time:.6f} seconds")
print(f"Speed ratio             : {list_time / numpy_time:.2f}x")

Python list comprehension: 0.169498 seconds
NumPy vectorization     : 0.013296 seconds
Speed ratio             : 12.75x


### Main lesson

Instead of:

```python
for i in range(len(x)):
    y[i] = x[i] * 2 + 1
```

prefer:

```python
y = x * 2 + 1
```

This is called **vectorization**.

NumPy pushes many operations into optimized compiled implementations, reducing Python-level loop overhead.

## 45. Vectorized normalization — common ML operation

In [63]:
# Suppose each row represents one student's marks in three subjects.
X = np.array([
    [80, 70, 90],
    [60, 75, 85],
    [90, 95, 88]
], dtype=float)

# Standardization column-wise:
# z = (x - mean) / standard deviation
mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print("Mean:", mean)
print("Std :", std)
print("\nStandardized data:\n", X_standardized)

print("\nNew column means:", X_standardized.mean(axis=0))
print("New column stds :", X_standardized.std(axis=0))

Mean: [76.66666667 80.         87.66666667]
Std : [12.47219129 10.8012345   2.05480467]

Standardized data:
 [[ 0.26726124 -0.9258201   1.13554995]
 [-1.33630621 -0.46291005 -1.29777137]
 [ 1.06904497  1.38873015  0.16222142]]

New column means: [-2.96059473e-16 -7.40148683e-17 -2.29446092e-15]
New column stds : [1. 1. 1.]


## 46. Min-Max normalization

In [64]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
], dtype=float)

X_min = X.min(axis=0)
X_max = X.max(axis=0)

X_scaled = (X - X_min) / (X_max - X_min)

print("Original:\n", X)
print("\nMin:", X_min)
print("Max:", X_max)
print("\nScaled:\n", X_scaled)

Original:
 [[ 10. 100.]
 [ 20. 200.]
 [ 30. 300.]
 [ 40. 400.]]

Min: [ 10. 100.]
Max: [ 40. 400.]

Scaled:
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


## 47. Pairwise distance example

In [65]:
# Three points in 2-D
points = np.array([
    [1, 2],
    [4, 6],
    [7, 3]
], dtype=float)

# Difference between every pair of points using broadcasting
diff = points[:, np.newaxis, :] - points[np.newaxis, :, :]

# Euclidean distance
distances = np.sqrt(np.sum(diff**2, axis=2))

print("Points:\n", points)
print("\nPairwise distance matrix:\n", distances)

Points:
 [[1. 2.]
 [4. 6.]
 [7. 3.]]

Pairwise distance matrix:
 [[0.         5.         6.08276253]
 [5.         0.         4.24264069]
 [6.08276253 4.24264069 0.        ]]


This pattern is useful in:

- K-Nearest Neighbors
- clustering
- recommender systems
- graph construction
- similarity search

The important idea is to use broadcasting rather than writing nested Python loops.

## 48. Cosine similarity

In [66]:
def cosine_similarity(a, b):
    # Convert inputs to NumPy arrays for consistent behavior.
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)

    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 6])
v3 = np.array([3, 0, 1])

print("cos(v1, v2):", cosine_similarity(v1, v2))
print("cos(v1, v3):", cosine_similarity(v1, v3))

cos(v1, v2): 1.0
cos(v1, v3): 0.50709255283711


## 49. np.asarray() and np.array()

In [67]:
# np.asarray is useful when a function should accept array-like input.
def describe(values):
    values = np.asarray(values)
    print("Array:", values)
    print("Shape:", values.shape)
    print("dtype:", values.dtype)

describe([1, 2, 3, 4])
describe((10, 20, 30))

Array: [1 2 3 4]
Shape: (4,)
dtype: int64
Array: [10 20 30]
Shape: (3,)
dtype: int64


## 50. Useful conditional utilities

In [68]:
x = np.array([10, 20, 30, 40, 50])

print("Any value > 45?", np.any(x > 45))
print("All values > 5?", np.all(x > 5))
print("All values even?", np.all(x % 2 == 0))
print("Any value divisible by 7?", np.any(x % 7 == 0))

Any value > 45? True
All values > 5? True
All values even? True
Any value divisible by 7? False


## 51. Clipping values

In [ ]:
scores = np.array([10, 35, 55, 78, 110])

# Restrict values to the range [0, 100]
clipped = np.clip(scores, 0, 100)

print("Original:", scores)
print("Clipped :", clipped)

Original: [ 10  35  55  78 110]
Clipped : [ 10  35  55  78 100]


## 52. Cumulative operations

In [70]:
sales = np.array([10, 15, 12, 20, 18])

print("Cumulative sum:", np.cumsum(sales))
print("Cumulative product:", np.cumprod(np.array([1, 2, 3, 4])))

print("Differences:", np.diff(sales))

Cumulative sum: [10 25 37 57 75]
Cumulative product: [ 1  2  6 24]
Differences: [ 5 -3  8 -2]


## 53. Percentiles and quantiles

In [71]:
marks = np.array([45, 50, 55, 60, 65, 70, 75, 80, 90])

print("25th percentile:", np.percentile(marks, 25))
print("50th percentile:", np.percentile(marks, 50))
print("75th percentile:", np.percentile(marks, 75))

print("Quantiles:", np.quantile(marks, [0.25, 0.5, 0.75]))

25th percentile: 55.0
50th percentile: 65.0
75th percentile: 75.0
Quantiles: [55. 65. 75.]


## 54. Histogram counts using NumPy

In [72]:
data = np.array([10, 12, 15, 18, 21, 23, 25, 28, 31, 33, 35])

counts, edges = np.histogram(data, bins=4)

print("Counts:", counts)
print("Bin edges:", edges)

Counts: [3 2 3 3]
Bin edges: [10.   16.25 22.5  28.75 35.  ]


## 55. Random dataset for a mini ML example

In [73]:
rng = np.random.default_rng(42)

n_samples = 100
n_features = 3

# Feature matrix: rows = samples, columns = features
X = rng.normal(size=(n_samples, n_features))

# A synthetic target
weights = np.array([2.0, -1.5, 0.5])
noise = rng.normal(scale=0.2, size=n_samples)

y = X @ weights + noise

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nFirst 5 X rows:\n", X[:5])
print("\nFirst 5 y values:", y[:5])

X shape: (100, 3)
y shape: (100,)

First 5 X rows:
 [[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934]]

First 5 y values: [ 2.89010596  3.84982018  0.89440972 -2.70199389 -1.33731061]


## 56. Train/test split using only NumPy

In [74]:
rng = np.random.default_rng(42)

X = rng.normal(size=(100, 4))
y = rng.integers(0, 2, size=100)

# Shuffle indices
indices = rng.permutation(len(X))

split = int(0.8 * len(X))
train_idx = indices[:split]
test_idx = indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (80, 4)
X_test : (20, 4)
y_train: (80,)
y_test : (20,)


## 57. One-hot encoding using NumPy

In [75]:
labels = np.array([0, 2, 1, 2, 0])
num_classes = 3

one_hot = np.eye(num_classes, dtype=int)[labels]

print("Labels:", labels)
print("\nOne-hot encoded:\n", one_hot)

Labels: [0 2 1 2 0]

One-hot encoded:
 [[1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


## 58. Argmax for classification

In [76]:
# Each row contains model scores/probabilities for three classes.
scores = np.array([
    [0.1, 0.7, 0.2],
    [0.8, 0.1, 0.1],
    [0.2, 0.3, 0.5]
])

predicted_classes = np.argmax(scores, axis=1)

print("Scores:\n", scores)
print("\nPredicted classes:", predicted_classes)

Scores:
 [[0.1 0.7 0.2]
 [0.8 0.1 0.1]
 [0.2 0.3 0.5]]

Predicted classes: [1 0 2]


## 59. A small NumPy-based linear regression calculation

In [77]:
# Generate synthetic y = Xw + noise
rng = np.random.default_rng(10)

X = rng.normal(size=(200, 2))
true_w = np.array([3.0, -2.0])
true_b = 5.0
noise = rng.normal(scale=0.5, size=200)

y = X @ true_w + true_b + noise

# Add a column of ones to learn the intercept together with weights.
X_design = np.column_stack([np.ones(len(X)), X])

# Least-squares solution
theta, residuals, rank, singular_values = np.linalg.lstsq(
    X_design, y, rcond=None
)

print("Estimated intercept:", theta[0])
print("Estimated weights  :", theta[1:])
print("True intercept     :", true_b)
print("True weights       :", true_w)

Estimated intercept: 5.011859761965566
Estimated weights  : [ 3.01887045 -2.00708332]
True intercept     : 5.0
True weights       : [ 3. -2.]


## 60. Common NumPy mistakes

In [78]:
# Mistake 1: using * when you mean matrix multiplication
A = np.eye(2)
B = np.ones((2, 2))

print("A * B = element-wise multiplication")
print(A * B)

print("\nA @ B = matrix multiplication")
print(A @ B)

A * B = element-wise multiplication
[[1. 0.]
 [0. 1.]]

A @ B = matrix multiplication
[[1. 1.]
 [1. 1.]]


### Common mistakes to discuss with students

1. **Confusing shape and size**
   - `(3, 4)` is a shape.
   - `12` is the size.

2. **Confusing `*` and `@`**
   - `*` is element-wise.
   - `@` is matrix multiplication.

3. **Forgetting `axis`**
   - Always ask: "Which dimension am I collapsing?"

4. **Using Python `and` / `or`**
   - Use `&` / `|` for element-wise array conditions.

5. **Accidental modification through a view**
   - Use `.copy()` when an independent array is required.

6. **Ignoring dtype**
   - Integer arrays cannot store fractional values correctly.

7. **Using `np.linalg.inv()` unnecessarily**
   - Prefer `np.linalg.solve()` for solving linear systems.

8. **Writing slow Python loops**
   - Look for a vectorized NumPy operation.

9. **Ignoring broadcasting rules**
   - Check the shapes before performing operations.

10. **Assuming `np.empty()` initializes to zero**
    - It does not.

## 61. Broadcasting exercise: predict before running

In [79]:
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30, 40])

print("A shape:", A.shape)
print("B shape:", B.shape)

result = A + B

print("\nResult:\n", result)
print("Result shape:", result.shape)

A shape: (3, 1)
B shape: (4,)

Result:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
Result shape: (3, 4)


## 62. Mini exercise set — students solve first

### Exercise 1
Create an array containing the numbers 1 to 100 and calculate:
- sum
- mean
- median
- standard deviation
- minimum
- maximum

### Exercise 2
Given:

`marks = np.array([45, 67, 32, 89, 76, 54, 91, 38])`

Find:
- all students scoring at least 50
- all students scoring between 60 and 80
- the highest mark and its index
- the number of students who passed

### Exercise 3
Create a `5 x 5` matrix containing numbers 1–25. Extract:
- first row
- last column
- center element
- top-left `3 x 3`
- all even numbers

### Exercise 4
Create a `10 x 3` feature matrix and standardize every column.

### Exercise 5
Generate 10,000 normally distributed random values and calculate their mean and standard deviation.

### Exercise 6
Given two vectors, calculate their:
- dot product
- L1 norm
- L2 norm
- cosine similarity

### Exercise 7
Create two matrices and demonstrate the difference between:
- element-wise multiplication
- matrix multiplication

## 63. Exercise solutions

In [80]:
# Exercise 1
x = np.arange(1, 101)

print("sum:", np.sum(x))
print("mean:", np.mean(x))
print("median:", np.median(x))
print("std:", np.std(x))
print("min:", np.min(x))
print("max:", np.max(x))


# Exercise 2
marks = np.array([45, 67, 32, 89, 76, 54, 91, 38])

print("\n>= 50:", marks[marks >= 50])
print("60 to 80:", marks[(marks >= 60) & (marks <= 80)])
print("Highest:", np.max(marks))
print("Highest index:", np.argmax(marks))
print("Number passed:", np.sum(marks >= 40))

sum: 5050
mean: 50.5
median: 50.5
std: 28.86607004772212
min: 1
max: 100

>= 50: [67 89 76 54 91]
60 to 80: [67 76]
Highest: 91
Highest index: 6
Number passed: 6


In [81]:
# Exercise 3
A = np.arange(1, 26).reshape(5, 5)

print("A:\n", A)
print("First row:", A[0])
print("Last column:", A[:, -1])
print("Center element:", A[2, 2])
print("Top-left 3x3:\n", A[:3, :3])
print("Even numbers:", A[A % 2 == 0])

A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Center element: 13
Top-left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20 22 24]


In [82]:
# Exercise 4
rng = np.random.default_rng(42)
X = rng.normal(size=(10, 3))

mean = X.mean(axis=0)
std = X.std(axis=0)

X_standardized = (X - mean) / std

print("Column means:", X_standardized.mean(axis=0))
print("Column stds :", X_standardized.std(axis=0))

Column means: [ 6.66133815e-17 -8.88178420e-17 -3.33066907e-17]
Column stds : [1. 1. 1.]


In [83]:
# Exercise 5
rng = np.random.default_rng(42)
samples = rng.normal(loc=0, scale=1, size=10_000)

print("Mean:", samples.mean())
print("Std :", samples.std())

Mean: -0.01024987541401165
Std : 1.006285768537041


In [84]:
# Exercise 6
a = np.array([1, 2, 3], dtype=float)
b = np.array([4, 5, 6], dtype=float)

dot = np.dot(a, b)
l1 = np.linalg.norm(a, ord=1)
l2 = np.linalg.norm(a)
cosine = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

print("Dot product:", dot)
print("L1 norm:", l1)
print("L2 norm:", l2)
print("Cosine similarity:", cosine)

Dot product: 32.0
L1 norm: 6.0
L2 norm: 3.7416573867739413
Cosine similarity: 0.9746318461970762


In [85]:
# Exercise 7
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise:\n", A * B)
print("\nMatrix multiplication:\n", A @ B)

Element-wise:
 [[ 5 12]
 [21 32]]

Matrix multiplication:
 [[19 22]
 [43 50]]


# 64. Final NumPy Cheat Sheet

### Array creation
- `np.array()`
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.empty()`
- `np.eye()`
- `np.arange()`
- `np.linspace()`
- `np.logspace()`

### Inspection
- `.ndim`
- `.shape`
- `.size`
- `.dtype`
- `.itemsize`
- `.nbytes`

### Indexing/slicing
- `a[i]`
- `a[start:stop:step]`
- `A[row, col]`
- `A[:, col]`
- `A[row, :]`

### Reshaping
- `.reshape()`
- `.flatten()`
- `.ravel()`
- `.T`
- `np.transpose()`
- `np.squeeze()`
- `np.expand_dims()`

### Combining
- `np.concatenate()`
- `np.stack()`
- `np.hstack()`
- `np.vstack()`
- `np.hsplit()`
- `np.vsplit()`

### Math
- `np.sum()`
- `np.mean()`
- `np.median()`
- `np.std()`
- `np.var()`
- `np.min()`
- `np.max()`
- `np.sqrt()`
- `np.exp()`
- `np.log()`
- `np.sin()`
- `np.cos()`

### Selection
- Boolean masking
- `np.where()`
- `np.any()`
- `np.all()`
- `np.clip()`

### Searching
- `np.argmax()`
- `np.argmin()`
- `np.argsort()`
- `np.unique()`

### Random
- `np.random.default_rng()`
- `.integers()`
- `.random()`
- `.normal()`
- `.choice()`
- `.permutation()`

### Linear algebra
- `A @ B`
- `np.dot()`
- `np.linalg.solve()`
- `np.linalg.det()`
- `np.linalg.inv()`
- `np.linalg.eig()`
- `np.linalg.norm()`
- `np.linalg.lstsq()`

### Missing values
- `np.isnan()`
- `np.nanmean()`
- `np.nansum()`
- `np.nanmin()`
- `np.nanmax()`

### Most important concepts for B.Tech students

**1. Shape → 2. Axis → 3. Broadcasting → 4. Vectorization → 5. Indexing/Masking → 6. Linear Algebra**

These six concepts form the foundation for using NumPy effectively in **Machine Learning, Deep Learning, Data Science, Computer Vision, NLP, Recommender Systems and Scientific Computing**.

# 65. Suggested next step

After completing this notebook, students should move to:

1. **Pandas** — data manipulation and tabular data
2. **Matplotlib / Seaborn** — visualization
3. **Scikit-learn** — machine learning
4. **PyTorch / TensorFlow** — deep learning
5. **SciPy** — scientific computing

A strong understanding of NumPy will make all of these libraries considerably easier to learn.